name: Votifier
main: com.vexsoftware.votifier.Votifier
description: A plugin that gets notified when votes are made for the server on toplists.
authors: [Woolyenough, blakeman8192, Kramer]
version: '4.0.0'
api-version: 1.21