name: Votifier
main: com.vexsoftware.votifier.Votifier
description: Fork of Votifier for the newer versions of Paper.
authors: [Woolyenough, blakeman8192, Kramer]
website: https://github.com/Woolyenough/votifier
version: '4.0.0'
api-version: 1.21